# EDA

In [3]:
import pandas as pd

df = pd.read_csv('mission15_train.csv')

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     7000 non-null   int64
 1   Previous Scores                   7000 non-null   int64
 2   Extracurricular Activities        7000 non-null   object
 3   Sleep Hours                       7000 non-null   int64
 4   Sample Question Papers Practiced  7000 non-null   int64
 5   Performance Index                 7000 non-null   float64
dtypes: float64(1), int64(4), object(1)
memory usage: 328.3+ KB
None

In [7]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({'Yes': 1, 'No': 0})

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     7000 non-null   int64
 1   Previous Scores                   7000 non-null   int64
 2   Extracurricular Activities        7000 non-null   int64
 3   Sleep Hours                       7000 non-null   int64
 4   Sample Question Papers Practiced  7000 non-null   int64
 5   Performance Index                 7000 non-null   float64
dtypes: float64(1), int64(5)
memory usage: 328.3 KB
None

In [8]:
df.describe()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000
mean,4.950000,69.429714,0.496857,6.530571,4.607429,55.095143
std,2.590621,17.289197,0.500026,1.696144,2.863550,19.151574
min,1.000000,40.000000,0.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,0.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,0.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,1.000000,8.000000,7.000000,70.000000
max,9.000000,99.000000,1.000000,9.000000,9.000000,100.000000

목표변수 상관관계 확인

perfirmance index - Previous Scores = 0.91

In [9]:
df.corr()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.015023,0.010357,0.010656,0.012049,0.374150
Previous Scores,-0.015023,1.000000,0.006123,0.001959,0.016089,0.913866
Extracurricular Activities,0.010357,0.006123,1.000000,-0.008478,0.017898,0.025306
Sleep Hours,0.010656,0.001959,-0.008478,1.000000,0.014356,0.049278
Sample Question Papers Practiced,0.012049,0.016089,0.017898,0.014356,1.000000,0.049908
Performance Index,0.374150,0.913866,0.025306,0.049278,0.049908,1.000000

# 모델링

## train 데이터셋 라벨 값 분리

In [ ]:
y = df['Performance Index'] 
X = df.drop('Performance Index', axis=1)

In [ ]:
import train_test_split